# Generated by Django 5.2.4 on 2025-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Review", "0003_customuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="Created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
